export const data = [
    [101, "tolga aşıkoğlu", "alaattin alperen karaca"],
    [103, "bünyamin şahin"],
    [104, "mustafa sınava", "kaan eliaçık"],
    [105, "kenan akpınar", "ali demirdere"],
    [107, "mert gazi tufan", "mahmut piliğ"],
    [110, "mustafa davulcu", "hüseyin tahtacı"],
    [201, "ahmet bakışgan", "aydın yüksel"],
    [204, "şükrü demirli", "kemal can"],
    [205, " ibrahim ballıkkaya", "halil can yılmaz"],
    [207, "emrullah şen", "cemallettin özdemir"],
    [210, "muhammet şentürk", "mustafa bilan"],
    [301, "alper metin", "sadık şimşek"],
    [304, "vahdettin doğan", "ercan boruç"],
    [305, "derami ahlat", "fatih can uysal"],
    [306, "murat çıkık"],
    [307, "mustafa şahin", "hazar kaymak"],
    [309, "tuğrul bıdak"],
];
