export const data = [
    [
        101,
        "tolga aşıkoğlu",
        "alaattin alperen karaca",

        ["giriş", "14-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "14000"],
    ],
    [
        103,
        "bünyamin şahin",
        "",
        ["giriş", "14-04-Pazar"],
        ["çıkış", "21-04-Pazar"],
        ["total", "9000"],
        ["not", "18'inde çıkıp, 19'uda geri geldi"],
    ],
    [
        104,
        "mustafa sınava",
        "kaan eliaçık",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        105,
        "kenan akpınar",
        "ali demirdere",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        107,
        "mert gazi tufan",
        "mahmut piliğ",
        ["giriş", "14-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "13500"],
        ["not", "18'inde tek kaldı."],
    ],
    [
        110,
        "mustafa davulcu",
        "hüseyin tahtacı",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        201,
        "ahmet bakışgan",
        "aydın yüksel",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        204,
        "şükrü demirli",
        "kemal can",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        205,
        " ibrahim ballıkkaya",
        "halil can yılmaz",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        207,
        "emrullah şen",
        "cemallettin özdemir",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        210,
        "muhammet şentürk",
        "mustafa bilan",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "15500"],
        ["not", "Ilk gece tek kişi kaldı."],
    ],
    [
        301,
        "alper metin",
        "sadık şimşek",
        ["giriş", "14-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "14000"],
    ],
    [
        302,
        "hacı yılmaz",
        "",
        ["giriş", "19-04-Cumartesi"],
        ["çıkış", "20-04-Pazar"],
        ["total", "1500"],
    ],
    [
        304,
        "vahdettin doğan",
        "ercan boruç",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        305,
        "derami ahlat",
        "fatih can uysal",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        306,
        "murat çıkık",
        "",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "12000"],
    ],
    [
        307,
        "mustafa şahin",
        "hazar kaymak",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "16000"],
    ],
    [
        309,
        "tuğrul bıdak",
        "",
        ["giriş", "13-04-Cumartesi"],
        ["çıkış", "21-04-Pazar"],
        ["total", "12500"],
        ["not", "Ilk gece çift kişi kaldı."],
    ],
    [
        302,
        "recep günaydın",
        "",
        ["giriş", "19-04-Cumartesi"],
        ["çıkış", "20-04-Pazar"],
        ["total", "1500"],
    ],
];
