export const data = [
    {
        id: undefined,
        name: undefined,
        financials: [
            {
                year: 2023,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2022,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2021,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2020,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2019,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2018,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2017,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2016,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2022,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2021,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2020,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2019,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2018,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2017,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2016,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2022,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2021,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2020,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2019,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2018,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2017,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2016,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
        ],
    },
    {
        id: "a1cap",
        name: "a1 capital yatırım",
        financials: [
            {
                year: 2023,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2022,
                net_sales: 15159.07,
                ebidta: 816.8,
                net_profit: 571.39,
                equity: 867.92,
                total_assets: 2504.21,
            },
            {
                year: 2021,
                net_sales: 6383.98,
                ebidta: 175.31,
                net_profit: 107.85,
                equity: 296.63,
                total_assets: 893.55,
            },
            {
                year: 2020,
                net_sales: 3258.37,
                ebidta: 83.58,
                net_profit: 73.17,
                equity: 138.79,
                total_assets: 467.53,
            },
            {
                year: 2019,
                net_sales: 596.6,
                ebidta: 5.4,
                net_profit: 5.07,
                equity: 65.57,
                total_assets: 196.89,
            },
            {
                year: 2018,
                net_sales: 1171.89,
                ebidta: 5.99,
                net_profit: 13.14,
                equity: 49.04,
                total_assets: 125.85,
            },
            {
                year: 2017,
                net_sales: 675.88,
                ebidta: -4.27,
                net_profit: 0.32,
                equity: 31.9,
                total_assets: 88.67,
            },
            {
                year: 2016,
                net_sales: 76.55,
                ebidta: -0.48,
                net_profit: 3.95,
                equity: 30.23,
                total_assets: 86.27,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2022,
                gross_profit_margin: 6.6,
                ebidta_margin: 5.39,
                net_profit_margin: 3.77,
                roe: 98.13,
                roa: 33.63,
            },
            {
                year: 2021,
                gross_profit_margin: 4.25,
                ebidta_margin: 2.75,
                net_profit_margin: 1.69,
                roe: 49.54,
                roa: 15.85,
            },
            {
                year: 2020,
                gross_profit_margin: 4.54,
                ebidta_margin: 2.57,
                net_profit_margin: 2.25,
                roe: 71.61,
                roa: 22.03,
            },
            {
                year: 2019,
                gross_profit_margin: 6.77,
                ebidta_margin: 0.9,
                net_profit_margin: 0.85,
                roe: 8.84,
                roa: 3.14,
            },
            {
                year: 2018,
                gross_profit_margin: 3.38,
                ebidta_margin: 0.51,
                net_profit_margin: 1.12,
                roe: 32.46,
                roa: 12.25,
            },
            {
                year: 2017,
                gross_profit_margin: 2.99,
                ebidta_margin: -0.63,
                net_profit_margin: 0.05,
                roe: 1.03,
                roa: 0.37,
            },
            {
                year: 2016,
                gross_profit_margin: 31.17,
                ebidta_margin: -0.62,
                net_profit_margin: 5.16,
                roe: 13.68,
                roa: 5.72,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2022,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2021,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2020,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2019,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2018,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2017,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2016,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
        ],
    },
    {
        id: "acsel",
        name: "acıpayam selüloz",
        financials: [
            {
                year: 2023,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2022,
                net_sales: 328.58,
                ebidta: 57.96,
                net_profit: 89.08,
                equity: 187.27,
                total_assets: 270.2,
            },
            {
                year: 2021,
                net_sales: 111.03,
                ebidta: 19.73,
                net_profit: 35.06,
                equity: 89.56,
                total_assets: 128.65,
            },
            {
                year: 2020,
                net_sales: 47.66,
                ebidta: 9.21,
                net_profit: 10.45,
                equity: 51.98,
                total_assets: 61.36,
            },
            {
                year: 2019,
                net_sales: 42.94,
                ebidta: 5.49,
                net_profit: 9.31,
                equity: 41.88,
                total_assets: 49.45,
            },
            {
                year: 2018,
                net_sales: 31.97,
                ebidta: 4.14,
                net_profit: 8.22,
                equity: 31.71,
                total_assets: 38.17,
            },
            {
                year: 2017,
                net_sales: 21.16,
                ebidta: 1.08,
                net_profit: 1.84,
                equity: 23.19,
                total_assets: 28.32,
            },
            {
                year: 2016,
                net_sales: 14.45,
                ebidta: 0.62,
                net_profit: 0.69,
                equity: 22.03,
                total_assets: 24.13,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2022,
                gross_profit_margin: 21.9,
                ebidta_margin: 17.64,
                net_profit_margin: 27.11,
                roe: 64.36,
                roa: 44.67,
            },
            {
                year: 2021,
                gross_profit_margin: 21.77,
                ebidta_margin: 17.77,
                net_profit_margin: 31.58,
                roe: 49.54,
                roa: 36.9,
            },
            {
                year: 2020,
                gross_profit_margin: 26.58,
                ebidta_margin: 19.33,
                net_profit_margin: 21.93,
                roe: 22.27,
                roa: 18.86,
            },
            {
                year: 2019,
                gross_profit_margin: 18.95,
                ebidta_margin: 12.78,
                net_profit_margin: 21.67,
                roe: 25.29,
                roa: 21.24,
            },
            {
                year: 2018,
                gross_profit_margin: 19.18,
                ebidta_margin: 12.96,
                net_profit_margin: 25.7,
                roe: 29.93,
                roa: 24.72,
            },
            {
                year: 2017,
                gross_profit_margin: 17.17,
                ebidta_margin: 5.12,
                net_profit_margin: 8.69,
                roe: 8.14,
                roa: 7.01,
            },
            {
                year: 2016,
                gross_profit_margin: 15.99,
                ebidta_margin: 4.26,
                net_profit_margin: 4.76,
                roe: 3.72,
                roa: 3.37,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2022,
                price: 76.73,
                "p/e": 9.25,
                "pd/ds": 4.4,
                "fd/ebidta": 14.94,
                "fd/sales": 14.94,
                eps: 8.31,
            },
            {
                year: 2021,
                price: 17.82,
                "p/e": 5.47,
                "pd/ds": 2.14,
                "fd/ebidta": 9.25,
                "fd/sales": 1.64,
                eps: 3.27,
            },
            {
                year: 2020,
                price: 16.95,
                "p/e": 17.56,
                "pd/ds": 3.53,
                "fd/ebidta": 19.31,
                "fd/sales": 3.73,
                eps: 0.97,
            },
            {
                year: 2019,
                price: 6.25,
                "p/e": 7.34,
                "pd/ds": 1.63,
                "fd/ebidta": 12.05,
                "fd/sales": 1.54,
                eps: 0.87,
            },
            {
                year: 2018,
                price: 3.14,
                "p/e": 4.25,
                "pd/ds": 1.1,
                "fd/ebidta": 8.02,
                "fd/sales": 1.04,
                eps: 0.77,
            },
            {
                year: 2017,
                price: 2.49,
                "p/e": 15.45,
                "pd/ds": 1.23,
                "fd/ebidta": 25.55,
                "fd/sales": 1.31,
                eps: 0.17,
            },
            {
                year: 2016,
                price: 2.85,
                "p/e": 47.98,
                "pd/ds": 1.5,
                "fd/ebidta": 52.03,
                "fd/sales": 2.22,
                eps: 0.06,
            },
        ],
    },
    {
        id: "adel",
        name: "adel kalemcilik",
        financials: [
            {
                year: 2023,
                net_sales: 2261.76,
                ebidta: 469.73,
                net_profit: 435.97,
                equity: 1110.83,
                total_assets: 2631.19,
            },
            {
                year: 2022,
                net_sales: 1675.12,
                ebidta: 84.35,
                net_profit: -19.43,
                equity: 692.68,
                total_assets: 1906.12,
            },
            {
                year: 2021,
                net_sales: 486.16,
                ebidta: 56.27,
                net_profit: -12.7,
                equity: 131.27,
                total_assets: 708.26,
            },
            {
                year: 2020,
                net_sales: 391.15,
                ebidta: 54.29,
                net_profit: 1.92,
                equity: 145.39,
                total_assets: 634.42,
            },
            {
                year: 2019,
                net_sales: 347.11,
                ebidta: 69.53,
                net_profit: -14.67,
                equity: 163.22,
                total_assets: 389.52,
            },
            {
                year: 2018,
                net_sales: 385.12,
                ebidta: 85.06,
                net_profit: 13.83,
                equity: 188.78,
                total_assets: 466.03,
            },
            {
                year: 2017,
                net_sales: 322.4,
                ebidta: 71.92,
                net_profit: 26.87,
                equity: 205.4,
                total_assets: 356.24,
            },
            {
                year: 2016,
                net_sales: 272.29,
                ebidta: 66.35,
                net_profit: 18.86,
                equity: 195.49,
                total_assets: 311.43,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: 46.69,
                ebidta_margin: 20.77,
                net_profit_margin: 19.28,
                roe: 48.35,
                roa: 19.22,
            },
            {
                year: 2022,
                gross_profit_margin: 25.19,
                ebidta_margin: 5.04,
                net_profit_margin: -1.16,
                roe: -4.72,
                roa: -1.49,
            },
            {
                year: 2021,
                gross_profit_margin: 31.65,
                ebidta_margin: 11.57,
                net_profit_margin: -2.61,
                roe: -9.18,
                roa: -1.89,
            },
            {
                year: 2020,
                gross_profit_margin: 38.04,
                ebidta_margin: 13.88,
                net_profit_margin: 0.49,
                roe: 1.24,
                roa: 0.37,
            },
            {
                year: 2019,
                gross_profit_margin: 43.74,
                ebidta_margin: 20.03,
                net_profit_margin: -4.23,
                roe: -8.34,
                roa: -3.43,
            },
            {
                year: 2018,
                gross_profit_margin: 45.25,
                ebidta_margin: 22.09,
                net_profit_margin: 3.59,
                roe: 7.02,
                roa: 3.36,
            },
            {
                year: 2017,
                gross_profit_margin: 45.16,
                ebidta_margin: 22.31,
                net_profit_margin: 8.33,
                roe: 13.41,
                roa: 8.05,
            },
            {
                year: 2016,
                gross_profit_margin: 47.54,
                ebidta_margin: 24.37,
                net_profit_margin: 6.93,
                roe: 9.4,
                roa: 5.46,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: 335.5,
                "p/e": 18.18,
                "pd/ds": 7.14,
                "fd/sales": 18.45,
                "fd/ebidta": 17.27,
                eps: 3.59,
            },
            {
                year: 2022,
                price: 112.34,
                "p/e": null,
                "pd/ds": 3.84,
                "fd/ebidta": 36.2,
                "fd/sales": 1.82,
                eps: -0.82,
            },
            {
                year: 2021,
                price: 32.34,
                "p/e": null,
                "pd/ds": 5.94,
                "fd/ebidta": 16.89,
                "fd/sales": 1.95,
                eps: -0.54,
            },
            {
                year: 2020,
                price: 32.7,
                "p/e": 431.05,
                "pd/ds": 5.68,
                "fd/ebidta": 17.32,
                "fd/sales": 2.4,
                eps: 0.08,
            },
            {
                year: 2019,
                price: 14.69,
                "p/e": null,
                "pd/ds": 2.27,
                "fd/ebidta": 7.69,
                "fd/sales": 1.54,
                eps: -0.62,
            },
            {
                year: 2018,
                price: 9.62,
                "p/e": 18.79,
                "pd/ds": 1.38,
                "fd/ebidta": 4.95,
                "fd/sales": 1.09,
                eps: 0.59,
            },
            {
                year: 2017,
                price: 13.57,
                "p/e": 14.47,
                "pd/ds": 1.89,
                "fd/ebidta": 6.54,
                "fd/sales": 1.46,
                eps: 1.14,
            },
            {
                year: 2016,
                price: 12.63,
                "p/e": 19.96,
                "pd/ds": 1.93,
                "fd/ebidta": 6.81,
                "fd/sales": 1.66,
                eps: 0.8,
            },
        ],
    },
    {
        id: "adese",
        name: "adese gayrimenkul",
        financials: [
            {
                year: 2023,
                net_sales: 335.86,
                ebidta: 117.86,
                net_profit: 1743.24,
                equity: 8441.3,
                total_assets: 9940.69,
            },
            {
                year: 2022,
                net_sales: 265.73,
                ebidta: 98.4,
                net_profit: 715.84,
                equity: 6583.17,
                total_assets: 7506.36,
            },
            {
                year: 2021,
                net_sales: 50.19,
                ebidta: 29.44,
                net_profit: 384.82,
                equity: 1924.33,
                total_assets: 2260.69,
            },
            {
                year: 2020,
                net_sales: 213.19,
                ebidta: -49.49,
                net_profit: -73.81,
                equity: 784.3,
                total_assets: 1553.49,
            },
            {
                year: 2019,
                net_sales: 198.99,
                ebidta: -32.08,
                net_profit: -0.5,
                equity: 585.34,
                total_assets: 1535.71,
            },
            {
                year: 2018,
                net_sales: 550.04,
                ebidta: -28.03,
                net_profit: -15.78,
                equity: 555.65,
                total_assets: 1218.54,
            },
            {
                year: 2017,
                net_sales: 693.5,
                ebidta: 30.18,
                net_profit: 43.92,
                equity: 562.87,
                total_assets: 1128.75,
            },
            {
                year: 2016,
                net_sales: 649.31,
                ebidta: 32.56,
                net_profit: 31.67,
                equity: 475.44,
                total_assets: 972.17,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: 49.78,
                ebidta_margin: 35.09,
                net_profit_margin: 519.03,
                roe: 23.21,
                roa: 19.98,
            },
            {
                year: 2022,
                gross_profit_margin: 49.19,
                ebidta_margin: 37.03,
                net_profit_margin: 269.39,
                roe: 16.83,
                roa: 14.66,
            },
            {
                year: 2021,
                gross_profit_margin: 91.41,
                ebidta_margin: 58.65,
                net_profit_margin: 766.74,
                roe: 28.41,
                roa: 20.18,
            },
            {
                year: 2020,
                gross_profit_margin: 23.16,
                ebidta_margin: -23.22,
                net_profit_margin: -34.62,
                roe: -10.78,
                roa: -4.78,
            },
            {
                year: 2019,
                gross_profit_margin: 27.96,
                ebidta_margin: -16.12,
                net_profit_margin: -0.25,
                roe: -0.09,
                roa: -0.04,
            },
            {
                year: 2018,
                gross_profit_margin: 20.98,
                ebidta_margin: -5.1,
                net_profit_margin: -2.87,
                roe: -2.82,
                roa: -1.34,
            },
            {
                year: 2017,
                gross_profit_margin: 23.04,
                ebidta_margin: 4.35,
                net_profit_margin: 6.33,
                roe: 8.46,
                roa: 4.18,
            },
            {
                year: 2016,
                gross_profit_margin: 23.21,
                ebidta_margin: 5.02,
                net_profit_margin: 4.88,
                roe: 6.89,
                roa: 3.45,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: 1.86,
                "p/e": 1.08,
                "pd/ds": 0.22,
                "fd/ebidta": 15.89,
                "fd/sales": 5.58,
                eps: 1.73,
            },
            {
                year: 2022,
                price: 1.99,
                "p/e": 2.8,
                "pd/ds": 0.3,
                "fd/ebidta": 14.53,
                "fd/sales": 5.38,
                eps: 0.71,
            },
            {
                year: 2021,
                price: 0.75,
                "p/e": 1.96,
                "pd/ds": 0.39,
                "fd/ebidta": 15.27,
                "fd/sales": 8.95,
                eps: 0.38,
            },
            {
                year: 2020,
                price: 2.42,
                "p/e": null,
                "pd/ds": 0.9,
                "fd/ebidta": -22.55,
                "fd/sales": 5.24,
                eps: -0.29,
            },
            {
                year: 2019,
                price: 1.24,
                "p/e": null,
                "pd/ds": 0.41,
                "fd/ebidta": -21.24,
                "fd/sales": 3.43,
                eps: 0.0,
            },
            {
                year: 2018,
                price: 1.51,
                "p/e": null,
                "pd/ds": 0.53,
                "fd/ebidta": -16.13,
                "fd/sales": 0.82,
                eps: -0.13,
            },
            {
                year: 2017,
                price: 1.28,
                "p/e": 5.71,
                "pd/ds": 0.45,
                "fd/ebidta": 13.65,
                "fd/sales": 0.59,
                eps: 0.35,
            },
            {
                year: 2016,
                price: 1.16,
                "p/e": 7.16,
                "pd/ds": 0.48,
                "fd/ebidta": 12.46,
                "fd/sales": 0.62,
                eps: 0.25,
            },
        ],
    },
    {
        id: "adgyo",
        name: "adra gmyo",
        financials: [
            {
                year: 2023,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2022,
                net_sales: 641.46,
                ebidta: 480.75,
                net_profit: 823.74,
                equity: 1196.0,
                total_assets: 1249.6,
            },
            {
                year: 2021,
                net_sales: 10.62,
                ebidta: 4.58,
                net_profit: 53.17,
                equity: 372.36,
                total_assets: 619.92,
            },
            {
                year: 2020,
                net_sales: 2.42,
                ebidta: 0.17,
                net_profit: 99.19,
                equity: 119.16,
                total_assets: 360.5,
            },
            {
                year: 2019,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
            {
                year: 2018,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
            {
                year: 2017,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
            {
                year: 2016,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2022,
                gross_profit_margin: 76.59,
                ebidta_margin: 74.95,
                net_profit_margin: 128.42,
                roe: 105.04,
                roa: 88.12,
            },
            {
                year: 2021,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2020,
                gross_profit_margin: 59.26,
                ebidta_margin: 43.16,
                net_profit_margin: 500.77,
                roe: 21.64,
                roa: 10.85,
            },
            {
                year: 2019,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
            {
                year: 2018,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
            {
                year: 2017,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
            {
                year: 2016,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2022,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: 2.8,
            },
            {
                year: 2021,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": 0.18,
                eps: null,
            },
            {
                year: 2020,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: 0.34,
            },
            {
                year: 2019,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2018,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2017,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2016,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
        ],
    },
    {
        id: "aefes",
        name: "anadolu efes",
        financials: [
            {
                year: 2023,
                net_sales: 159877.21,
                ebidta: 27045.49,
                net_profit: 22128.94,
                equity: 64557.72,
                total_assets: 265225.69,
            },
            {
                year: 2022,
                net_sales: 155060.05,
                ebidta: 25327.91,
                net_profit: 15384.19,
                equity: 64532.6,
                total_assets: 268244.57,
            },
            {
                year: 2021,
                net_sales: 39284.38,
                ebidta: 6447.29,
                net_profit: 1068.3,
                equity: 18715.08,
                total_assets: 85512.88,
            },
            {
                year: 2020,
                net_sales: 26742.69,
                ebidta: 4749.11,
                net_profit: 814.76,
                equity: 12805.76,
                total_assets: 50561.37,
            },
            {
                year: 2019,
                net_sales: 23076.56,
                ebidta: 3820.22,
                net_profit: 1034.16,
                equity: 13177.3,
                total_assets: 45898.13,
            },
            {
                year: 2018,
                net_sales: 18689.69,
                ebidta: 2713.64,
                net_profit: -11.68,
                equity: 11369.31,
                total_assets: 39696.17,
            },
            {
                year: 2017,
                net_sales: 12732.36,
                ebidta: 2101.01,
                net_profit: 149.42,
                equity: 9811.7,
                total_assets: 29529.63,
            },
            {
                year: 2016,
                net_sales: 10420.26,
                ebidta: 1646.3,
                net_profit: -70.8,
                equity: 9262.5,
                total_assets: 25628.56,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: 36.9,
                ebidta_margin: 16.92,
                net_profit_margin: 13.84,
                roe: 34.28,
                roa: 8.3,
            },
            {
                year: 2022,
                gross_profit_margin: 34.54,
                ebidta_margin: 16.33,
                net_profit_margin: 9.92,
                roe: 36.96,
                roa: 8.7,
            },
            {
                year: 2021,
                gross_profit_margin: 36.0,
                ebidta_margin: 16.41,
                net_profit_margin: 2.72,
                roe: 6.78,
                roa: 1.57,
            },
            {
                year: 2020,
                gross_profit_margin: 37.18,
                ebidta_margin: 17.76,
                net_profit_margin: 3.05,
                roe: 6.27,
                roa: 1.69,
            },
            {
                year: 2019,
                gross_profit_margin: 37.94,
                ebidta_margin: 16.55,
                net_profit_margin: 4.48,
                roe: 8.43,
                roa: 2.42,
            },
            {
                year: 2018,
                gross_profit_margin: 36.02,
                ebidta_margin: 14.52,
                net_profit_margin: -0.06,
                roe: -0.11,
                roa: -0.03,
            },
            {
                year: 2017,
                gross_profit_margin: 37.9,
                ebidta_margin: 16.5,
                net_profit_margin: 1.17,
                roe: 1.57,
                roa: 0.54,
            },
            {
                year: 2016,
                gross_profit_margin: 39.26,
                ebidta_margin: 15.8,
                net_profit_margin: -0.68,
                roe: -0.83,
                roa: -0.3,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: 137.5,
                "p/e": 3.68,
                "pd/ds": 1.26,
                "fd/ebidta": 3.7,
                "fd/sales": 0.63,
                eps: 37.37,
            },
            {
                year: 2022,
                price: 65.85,
                "p/e": 2.61,
                "pd/ds": 0.62,
                "fd/ebidta": 2.43,
                "fd/sales": 0.4,
                eps: 25.98,
            },
            {
                year: 2021,
                price: 27.02,
                "p/e": 16.42,
                "pd/ds": 0.94,
                "fd/ebidta": 4.41,
                "fd/sales": 0.72,
                eps: 1.8,
            },
            {
                year: 2020,
                price: 19.49,
                "p/e": 16.85,
                "pd/ds": 1.07,
                "fd/ebidta": 3.65,
                "fd/sales": 0.65,
                eps: 1.38,
            },
            {
                year: 2019,
                price: 17.89,
                "p/e": 13.21,
                "pd/ds": 1.04,
                "fd/ebidta": 4.72,
                "fd/sales": 0.78,
                eps: 1.75,
            },
            {
                year: 2018,
                price: 15.56,
                "p/e": null,
                "pd/ds": 1.07,
                "fd/ebidta": 6.25,
                "fd/sales": 0.91,
                eps: -0.02,
            },
            {
                year: 2017,
                price: 17.98,
                "p/e": 95.9,
                "pd/ds": 1.46,
                "fd/ebidta": 8.25,
                "fd/sales": 1.36,
                eps: 0.25,
            },
            {
                year: 2016,
                price: 12.95,
                "p/e": null,
                "pd/ds": 1.13,
                "fd/ebidta": 8.42,
                "fd/sales": 1.33,
                eps: -0.12,
            },
        ],
    },
    {
        id: "afyon",
        name: "afyon çimento",
        financials: [
            {
                year: 2023,
                net_sales: 2602.8,
                ebidta: 762.38,
                net_profit: 992.47,
                equity: 3971.22,
                total_assets: 4657.32,
            },
            {
                year: 2022,
                net_sales: 2455.91,
                ebidta: 575.59,
                net_profit: 155.58,
                equity: 3090.35,
                total_assets: 4265.54,
            },
            {
                year: 2021,
                net_sales: 413.48,
                ebidta: 81.81,
                net_profit: 76.89,
                equity: 566.68,
                total_assets: 800.48,
            },
            {
                year: 2020,
                net_sales: 270.31,
                ebidta: 42.24,
                net_profit: 17.06,
                equity: 490.68,
                total_assets: 705.59,
            },
            {
                year: 2019,
                net_sales: 163.33,
                ebidta: 15.84,
                net_profit: -61.0,
                equity: 171.69,
                total_assets: 648.32,
            },
            {
                year: 2018,
                net_sales: 175.2,
                ebidta: 55.67,
                net_profit: 3.92,
                equity: 232.71,
                total_assets: 661.36,
            },
            {
                year: 2017,
                net_sales: 168.15,
                ebidta: 51.72,
                net_profit: 54.01,
                equity: 228.86,
                total_assets: 789.19,
            },
            {
                year: 2016,
                net_sales: 60.83,
                ebidta: 3.31,
                net_profit: 9.6,
                equity: 174.84,
                total_assets: 589.25,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: 24.02,
                ebidta_margin: 29.29,
                net_profit_margin: 38.13,
                roe: 28.11,
                roa: 22.25,
            },
            {
                year: 2022,
                gross_profit_margin: 16.78,
                ebidta_margin: 23.44,
                net_profit_margin: 6.33,
                roe: 8.51,
                roa: 6.14,
            },
            {
                year: 2021,
                gross_profit_margin: 15.22,
                ebidta_margin: 19.78,
                net_profit_margin: 18.59,
                roe: 14.54,
                roa: 10.21,
            },
            {
                year: 2020,
                gross_profit_margin: 7.37,
                ebidta_margin: 15.62,
                net_profit_margin: 6.31,
                roe: 5.15,
                roa: 2.52,
            },
            {
                year: 2019,
                gross_profit_margin: -4.04,
                ebidta_margin: 9.7,
                net_profit_margin: -37.35,
                roe: -30.17,
                roa: -9.32,
            },
            {
                year: 2018,
                gross_profit_margin: 18.56,
                ebidta_margin: 31.78,
                net_profit_margin: -20.78,
                roe: 2.24,
                roa: 1.7,
            },
            {
                year: 2017,
                gross_profit_margin: 20.77,
                ebidta_margin: 30.76,
                net_profit_margin: 32.12,
                roe: 26.76,
                roa: 7.84,
            },
            {
                year: 2016,
                gross_profit_margin: 9.27,
                ebidta_margin: 5.45,
                net_profit_margin: 15.79,
                roe: 5.64,
                roa: 1.99,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: 11.1,
                "p/e": 4.47,
                "pd/ds": 1.12,
                "fd/ebidta": 5.47,
                "fd/sales": 1.6,
                eps: 2.48,
            },
            {
                year: 2022,
                price: 8.45,
                "p/e": 22.21,
                "pd/ds": 1.12,
                "fd/ebidta": 5.51,
                "fd/sales": 1.29,
                eps: 0.39,
            },
            {
                year: 2021,
                price: 3.37,
                "p/e": 18.16,
                "pd/ds": 2.46,
                "fd/ebidta": 18.26,
                "fd/sales": 3.61,
                eps: 0.19,
            },
            {
                year: 2020,
                price: 4.93,
                "p/e": 119.78,
                "pd/ds": 4.17,
                "fd/ebidta": 50.5,
                "fd/sales": 7.89,
                eps: 0.04,
            },
            {
                year: 2019,
                price: 2.2,
                "p/e": null,
                "pd/ds": 3.66,
                "fd/ebidta": 67.09,
                "fd/sales": 6.51,
                eps: -0.61,
            },
            {
                year: 2018,
                price: 1.61,
                "p/e": 117.0,
                "pd/ds": 1.97,
                "fd/ebidta": 15.16,
                "fd/sales": 4.82,
                eps: 0.04,
            },
            {
                year: 2017,
                price: 2.73,
                "p/e": 14.4,
                "pd/ds": 3.4,
                "fd/ebidta": 23.37,
                "fd/sales": 7.19,
                eps: 0.54,
            },
            {
                year: 2016,
                price: 2.77,
                "p/e": 82.38,
                "pd/ds": 4.52,
                "fd/ebidta": 352.1,
                "fd/sales": 19.18,
                eps: 0.1,
            },
        ],
    },
    {
        id: "agesa",
        name: "agesa hayat emeklilik",
        financials: [
            {
                year: 2023,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: 2951.05,
                total_assets: null,
            },
            {
                year: 2022,
                net_sales: null,
                ebidta: null,
                net_profit: 1325.28,
                equity: 1690.83,
                total_assets: null,
            },
            {
                year: 2021,
                net_sales: null,
                ebidta: null,
                net_profit: 178.33,
                equity: 882.06,
                total_assets: null,
            },
            {
                year: 2020,
                net_sales: null,
                ebidta: null,
                net_profit: 114.22,
                equity: 679.45,
                total_assets: null,
            },
            {
                year: 2019,
                net_sales: null,
                ebidta: null,
                net_profit: 158.6,
                equity: 514.26,
                total_assets: null,
            },
            {
                year: 2018,
                net_sales: null,
                ebidta: null,
                net_profit: 125.53,
                equity: 370.31,
                total_assets: null,
            },
            {
                year: 2017,
                net_sales: null,
                ebidta: null,
                net_profit: 147.93,
                equity: 264.05,
                total_assets: null,
            },
            {
                year: 2016,
                net_sales: null,
                ebidta: null,
                net_profit: 215.26,
                equity: 185.33,
                total_assets: null,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 59.19,
                roa: null,
            },
            {
                year: 2022,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 64.83,
                roa: null,
            },
            {
                year: 2021,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 57.42,
                roa: null,
            },
            {
                year: 2020,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 48.73,
                roa: null,
            },
            {
                year: 2019,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 47.29,
                roa: null,
            },
            {
                year: 2018,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 60.29,
                roa: null,
            },
            {
                year: 2017,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 45.26,
                roa: null,
            },
            {
                year: 2016,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: 37.16,
                roa: null,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: 61.05,
                "p/e": 8.0,
                "pd/ds": 3723754.93,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2022,
                price: 39.12,
                "p/e": 8.71,
                "pd/ds": 4294451.67,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2021,
                price: 19.9,
                "p/e": 8.24,
                "pd/ds": 4187492.14,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2020,
                price: 16.62,
                "p/e": 11.36,
                "pd/ds": 4861298.87,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2019,
                price: 12.14,
                "p/e": 12.0,
                "pd/ds": 4879265.73,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2018,
                price: 6.33,
                "p/e": 7.22,
                "pd/ds": 3728211.04,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2017,
                price: 9.57,
                "p/e": 21.03,
                "pd/ds": 8097673.97,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2016,
                price: 10.06,
                "p/e": 35.89,
                "pd/ds": 12243944.94,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
        ],
    },
    {
        id: "aghol",
        name: "anadolu grubu holding",
        financials: [
            {
                year: 2023,
                net_sales: 375583.48,
                ebidta: 34217.86,
                net_profit: 19638.48,
                equity: 64409.76,
                total_assets: 391799.43,
            },
            {
                year: 2022,
                net_sales: 319647.53,
                ebidta: 30917.99,
                net_profit: 15639.25,
                equity: 53964.85,
                total_assets: 377714.51,
            },
            {
                year: 2021,
                net_sales: 81368.49,
                ebidta: 10195.01,
                net_profit: 1290.78,
                equity: 8988.27,
                total_assets: 112291.85,
            },
            {
                year: 2020,
                net_sales: 62081.49,
                ebidta: 7944.99,
                net_profit: -350.65,
                equity: 5759.66,
                total_assets: 73272.99,
            },
            {
                year: 2019,
                net_sales: 44781.68,
                ebidta: 5628.91,
                net_profit: 564.87,
                equity: 6182.83,
                total_assets: 66429.54,
            },
            {
                year: 2018,
                net_sales: 23981.26,
                ebidta: 3322.82,
                net_profit: 19 - 1168.15,
                equity: 5130.06,
                total_assets: 48072.06,
            },
            {
                year: 2017,
                net_sales: 17163.69,
                ebidta: 2552.35,
                net_profit: -130.05,
                equity: 5681.72,
                total_assets: 37906.11,
            },
            {
                year: 2016,
                net_sales: 14149.93,
                ebidta: 1966.16,
                net_profit: -376.05,
                equity: 5709.68,
                total_assets: 32986.96,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: 26.44,
                ebidta_margin: 9.11,
                net_profit_margin: 5.23,
                roe: 33.18,
                roa: 5.1,
            },
            {
                year: 2022,
                gross_profit_margin: 25.96,
                ebidta_margin: 9.67,
                net_profit_margin: 4.89,
                roe: 49.69,
                roa: 6.38,
            },
            {
                year: 2021,
                gross_profit_margin: 29.84,
                ebidta_margin: 12.53,
                net_profit_margin: 1.59,
                roe: 17.5,
                roa: 1.39,
            },
            {
                year: 2020,
                gross_profit_margin: 29.16,
                ebidta_margin: 12.8,
                net_profit_margin: -0.56,
                roe: -5.87,
                roa: -0.5,
            },
            {
                year: 2019,
                gross_profit_margin: 30.54,
                ebidta_margin: 12.57,
                net_profit_margin: 1.26,
                roe: 9.99,
                roa: 0.99,
            },
            {
                year: 2018,
                gross_profit_margin: 32.03,
                ebidta_margin: 13.86,
                net_profit_margin: -4.87,
                roe: -21.61,
                roa: -2.72,
            },
            {
                year: 2017,
                gross_profit_margin: 32.55,
                ebidta_margin: 14.87,
                net_profit_margin: -0.76,
                roe: -2.28,
                roa: -0.37,
            },
            {
                year: 2016,
                gross_profit_margin: 32.95,
                ebidta_margin: 13.9,
                net_profit_margin: -2.66,
                roe: -8.14,
                roa: -1.8,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: 200.9,
                "p/e": 2.49,
                "pd/ds": 0.76,
                "fd/ebidta": 2.11,
                "fd/sales": 0.19,
                eps: 80.64,
            },
            {
                year: 2022,
                price: 109.42,
                "p/e": 1.72,
                "pd/ds": 0.5,
                "fd/ebidta": 1.78,
                "fd/sales": 0.17,
                eps: 64.22,
            },
            {
                year: 2021,
                price: 38.7,
                "p/e": 7.42,
                "pd/ds": 1.07,
                "fd/ebidta": 2.76,
                "fd/sales": 0.35,
                eps: 5.3,
            },
            {
                year: 2020,
                price: 25.71,
                "p/e": null,
                "pd/ds": 1.12,
                "fd/ebidta": 2.43,
                "fd/sales": 0.31,
                eps: -1.44,
            },

            {
                year: 2019,
                price: 17.12,
                "p/e": 7.58,
                "pd/ds": 0.69,
                "fd/ebidta": 3.36,
                "fd/sales": 0.42,
                eps: 2.32,
            },
            {
                year: 2018,
                price: 9.86,
                "p/e": null,
                "pd/ds": 0.49,
                "fd/ebidta": 4.06,
                "fd/sales": 0.56,
                eps: -4.8,
            },
            {
                year: 2017,
                price: 22.72,
                "p/e": null,
                "pd/ds": 0.67,
                "fd/ebidta": 4.7,
                "fd/sales": 0.7,
                eps: -0.81,
            },
            {
                year: 2016,
                price: 12.26,
                "p/e": null,
                "pd/ds": 0.54,
                "fd/ebidta": 21.91,
                "fd/sales": 1.94,
                eps: -1.51,
            },
        ],
    },
    {
        id: "agrot",
        name: "agrotech teknoloji",
        financials: [
            {
                year: 2023,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2022,
                net_sales: 465.76,
                ebidta: 207.43,
                net_profit: 225.29,
                equity: 1809.35,
                total_assets: 2509.09,
            },
            {
                year: 2021,
                net_sales: 206.69,
                ebidta: 26.24,
                net_profit: 28.07,
                equity: 782.9,
                total_assets: 1041.87,
            },
            {
                year: 2020,
                net_sales: 37.94,
                ebidta: -4.29,
                net_profit: 17.23,
                equity: 492.87,
                total_assets: 684.33,
            },
            {
                year: 2019,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
            {
                year: 2018,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
            {
                year: 2017,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
            {
                year: 2016,
                net_sales: null,
                ebidta: null,
                net_profit: null,
                equity: null,
                total_assets: null,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2022,
                gross_profit_margin: 48.61,
                ebidta_margin: 44.54,
                net_profit_margin: 48.37,
                roe: 17.38,
                roa: 12.69,
            },
            {
                year: 2021,
                gross_profit_margin: 14.89,
                ebidta_margin: 12.69,
                net_profit_margin: 13.58,
                roe: 4.4,
                roa: 3.25,
            },
            {
                year: 2020,
                gross_profit_margin: 13.35,
                ebidta_margin: -11.32,
                net_profit_margin: 45.41,
                roe: 3.5,
                roa: 2.52,
            },
            {
                year: 2019,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
            {
                year: 2018,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
            {
                year: 2017,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
            {
                year: 2016,
                gross_profit_margin: null,
                ebidta_margin: null,
                net_profit_margin: null,
                roe: null,
                roa: null,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2022,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: 0.19,
            },
            {
                year: 2021,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: 0.02,
            },
            {
                year: 2020,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: 0.01,
            },
            {
                year: 2019,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2018,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2017,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
            {
                year: 2016,
                price: null,
                "p/e": null,
                "pd/ds": null,
                "fd/ebidta": null,
                "fd/sales": null,
                eps: null,
            },
        ],
    },
];
