const mockData = [
    {
        id: undefined,
        name: undefined,
        sector: undefined,
        paidInCapital: undefined,
        pfr: undefined,
        financials: [
            {
                year: 2023,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2022,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2021,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2020,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2019,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2018,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2017,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
            {
                year: 2016,
                net_sales: undefined,
                ebidta: undefined,
                net_profit: undefined,
                equity: undefined,
                total_assets: undefined,
            },
        ],
        profitability: [
            {
                year: 2023,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2022,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2021,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2020,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2019,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2018,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2017,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
            {
                year: 2016,
                gross_profit_margin: undefined,
                ebidta_margin: undefined,
                net_profit_margin: undefined,
                roe: undefined,
                roa: undefined,
            },
        ],
        valuation: [
            {
                year: 2023,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2022,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2021,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2020,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2019,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2018,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2017,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
            {
                year: 2016,
                price: undefined,
                "p/e": undefined,
                "pd/ds": undefined,
                "fd/ebidta": undefined,
                "fd/sales": undefined,
                eps: undefined,
            },
        ],
    },
];
